image: python

branches:
  - release

script:
  - chmod +x ./.drone/*.sh
  - ./.drone/build.sh

deploy:  
  bash:
    script:
      - ./.drone/deploy.sh

  git:
    target: git@github.com:aplazame/aplazame-sdk.git
    branch: master
    force: true

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOOK_URL
    username: 'drone'
    on_success: change
    on_failure: false

  email:
    recipients:
      - dev@aplazame.com
    on_success: change
    on_failure: false
