image: python

script:
  - chmod +x ./.drone/*.sh
  - ./.drone/build.sh
deploy:  
  bash:
    script:
      - ./.drone/deploy.sh

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOOK_URL
    username: 'drone'
    on_success: change
    on_failure: true

  email:
    recipients:
      - dev@aplazame.com
    on_success: true
    on_failure: true
