image: python

script:
  - chmod +x ./.drone/build.sh
  - ./.drone/build.sh
deploy:  
  bash:
    script:
      - pwd
      - python -V

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    on_success: change
    on_failure: true

  email:
    recipients:
      - dev@aplazame.com
    on_success: true
    on_failure: true
