image: python

script:
  - chmod +x ./.drone/build.sh
  - ./.drone/build.sh
deploy:  
  bash:
    script:
      - pwd
      - python -V

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOOK_URL
    username: 'drone'
    on_success: true
    on_failure: true

  email:
    recipients:
      - dev@aplazame.com
    on_success: true
    on_failure: true
