image: python

branches:
  - master
  - release

script:
  - chmod +x ./.drone/*.sh
  - ./.drone/build.sh

deploy:
  bash:
    script:
      - ./.drone/pypi.sh
      - ./.drone/deploy.sh
    when:
      branch: release

  git:
    target: git@github.com:aplazame/aplazame-sdk.git
    branch: master
    force: false
    when:
      branch: release

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'aplazame-sdk'
    on_success: change
    on_failure: true

  email:
    recipients:
      - dev@aplazame.com
    on_success: change
    on_failure: true
